# Stage 1 - the build process
FROM node:8.11.3 as build-deps
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json yarn.lock /usr/src/app/
RUN yarn
COPY . /usr/src/app
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.13.3-alpine
RUN rm -rf /etc/nginx/conf.d
COPY nginx/default.conf /etc/nginx/conf.default
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]