version: '3.5'
services:
  prod-build:
    container_name: prod-build
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production