version: '3'
services:
  prod-build:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: prod-build
    restart: always
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production